name: mint
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3

  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.0
  analyzer: ^6.0.0
  auto_route_generator: ^10.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/data/